In [2]:
import numpy as np

In [8]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [9]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
print(a[0])

[1 2 3 4]


In [11]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
a[1]

array([5, 6, 7, 8])

In [13]:
# Kolom 1 , Baris 2 

a[1][2]

7

### MEMBUAT ARRAY DIISI DENGAN NOL

In [8]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

### MEMBUAT ARRAY DIISI DENGAN SATU

In [9]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

### MEMBUAT ARRAY KOSONG (EMPTY)

In [10]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

### MEMBUAT ARRAY DENGAN BEBERAPA JARAK

In [12]:
# nilai ada 4

print(np.arange(4))

[0 1 2 3]


In [13]:
# List dimulai dari 0-10, dengan kenaikan 2, tapi 10 tidak termasuk, 

print(np.arange(0, 10, 2))

[0 2 4 6 8]


In [ ]:
print(np.arange(2, 30, 5))

In [125]:
np.random(9)

TypeError: 'module' object is not callable

### ADD, REMOVE, SORT

In [ ]:
np.append()
np.delete()
np.sort

### NP.APPEND
Untuk menambahkan elemen ke array

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
np.append(arr, [1, 2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

### NP.DELETE
Menghapus elemen

In [5]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

### NP.SORT
Mengurutkan angka

In [6]:
arr = np.array([3, 2, 1, 4, 5, 6, 7, 8])

In [7]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### SHAPE AND SIZE

ndarray.ndim() "Memberi tahu jumlah axes, dimensi dari array"
ndarray.size() "Memberi tahu jumlah total elemen array"
ndarray.shape() "Memberi tahu jumlah baris dan kolom"

### CONTOH 1

In [16]:
array_example = np.array ([[[0,1,2,3], [4,5,6,7]],[[0,1,2,3], [4,5,6,7]], [[0,1,2,3],[4,5,6,7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [17]:
array_example.ndim

3

In [18]:
array_example.size

24

In [19]:
array_example.shape

(3, 2, 4)

### CONTOH 2

In [50]:
arr_one = np.array([1,2,3,4,5])

In [51]:
arr_one.ndim

1

In [52]:
arr_one.size

5

In [53]:
arr_one.shape

(5,)

### RESHAPE

np.reshape() "Memberi bentuk baru ke array tanpa mengubah data"
Array lama dan baru harus SAMA ELEMEN

a "array yang akan di reshape"
newshape "bentuk baru yg diinginkan"

## CONTOH 

In [32]:
a = np.arange(6)
print (a)

[0 1 2 3 4 5]


In [34]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [35]:
a.reshape (3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

### CONVERT 1D to 2D

np.newaxis "Meningkatkan array sebesar 1 dimensi"
np.expand_dims

### CONTOH 1

In [36]:
a = np.array ([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [37]:
a2 = a[np.newaxis]

In [38]:
print(a2)

[[1 2 3 4 5 6]]


In [39]:
print(a2.shape)

(1, 6)


### MENAMBAH 1 DIMENSI ARRAY MENGGUNAKAN (:) dibelakang

In [40]:
row_vector = a[np.newaxis, :]

In [41]:
print(row_vector)

[[1 2 3 4 5 6]]


In [42]:
print(row_vector.shape)

(1, 6)


### MENAMBAH (:) didepan untuk membuat array vertikal dan ditambah 1 dimensi

In [43]:
col_vector = a[:, np.newaxis]

In [44]:
print(col_vector)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [45]:
print(col_vector.shape)

# 6 kolom, 1 baris 

(6, 1)


### MENAMBAH KOLOM, NP.EXPAND_DIMS

In [46]:
a = np.array ([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [48]:
#Axis =baris

b = np.expand_dims(a, axis=1)

In [49]:
b.shape

(6, 1)

In [54]:
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### MENAMBAH 1 dimensi

In [59]:
c = np.expand_dims(a, axis=0)

In [60]:
c.shape

(1, 6)

In [61]:
print(c)

[[1 2 3 4 5 6]]


### INDEXING & SLICING

In [62]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


### CONTOH DATA

In [63]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [64]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### MENAMPILKAN ANGKA LEBIH BESAR SAMA DENGAN 5

### CONTOH 1

In [65]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


### CONTOH 2

In [66]:
five_up = (a>=5)

print(a[five_up])

[ 5  6  7  8  9 10 11 12]


### MENAMPILKAN ELEMEN HABIS DIBAGI 2

### DIVISIBLE

In [69]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [70]:
divisible_by_2 = a[a%2==0]

In [71]:
print(divisible_by_2)

[ 2  4  6  8 10 12]


### MENAMPILKAN ELEMEN > 2 dan < 11

In [72]:
c = a[(a > 2) & (a < 11)]

In [73]:
print(c)

[ 3  4  5  6  7  8  9 10]


### CREATING ARRAY FROM EXISTING DATA

slicing indexing
np.vstack()
np.hstack()
np.hsplit()
.view()
.copy()

In [74]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [75]:
arr1 = arr[3:8]

In [76]:
arr1

array([4, 5, 6, 7, 8])

### MENUMPUK ARRAY SECARA VERTIKAL

dengan vstack

In [77]:
a_1 = np.array([[1,1], [2,2]])

In [78]:
a_2 = np.array([[3,3], [4,4]])

In [84]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [86]:
a_1_2 = np.vstack((a_1, a_2))
print(a_1_2)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


### MENUMPUK ARRAY SECARA HORIZONTAL

dengan hstack

In [85]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

### MEMBAGI ARRAY MENJADI LEBIH KECIL

In [90]:
arr_split = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
                      [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [91]:
print(arr_split)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


### MEMBAGI ARRAY MENJADI 3 KOLOM SCR HORIZONTAL

In [92]:
np.hsplit(arr_split,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

### MEMBUAT ARRAY BARU YANG DATANYA SAMA DGN ARRAY ASLI

np.view
np.copy "Meng copy Data"

In [93]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [94]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
b = a.view()

In [96]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
c = a.copy() 

In [98]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### BASIC ARRAY OPERATIONS
Addition, subtraction, multiplication, division

data - ones 
data * data
data/data

np.sum "Menjumlahkan Semua Elemen di Array"

In [99]:
a = np.array ([1,2,3,4])

In [100]:
a.sum()

10

### Untuk tambah baris/kolom di array 2D, tentukan axis

In [101]:
b = np.array([[1,1], [2,2]])

In [102]:
b

array([[1, 1],
       [2, 2]])

In [103]:
# SUM ROWS

b.sum(axis=0)

array([3, 3])

In [105]:
# SUM COLUMS

b.sum(axis=1)

array([2, 4])

### CONTOH

In [107]:
data = np.array([1,2])
data

array([1, 2])

In [108]:
ones = np.ones(2)
ones

array([1., 1.])

In [109]:
data + ones

array([2., 3.])

In [110]:
data*data

array([1, 4])

In [111]:
data/data

array([1., 1.])

### BROADCASTING
Operasi antara array dan 1 bilangan

In [112]:
data*1.6

array([1.6, 3.2])

In [113]:
data*2

array([2, 4])

### MORE ARRAY OPERATIONS
Maximum, minimum, sum, mean, product, standard deviation

data.max()
data.min()
data.sum()

In [115]:
A = np.array([[0.45, 0.50, 0.30, 0.55],
             [0.66, 0.77, 0.68, 0.54],
             [0.34, 0.90, 0.80, 0.75]])

In [117]:
print(A)

[[0.45 0.5  0.3  0.55]
 [0.66 0.77 0.68 0.54]
 [0.34 0.9  0.8  0.75]]


In [118]:
A.sum()

7.24

In [119]:
A.min()

0.3

In [120]:
A.max()

0.9

In [121]:
# Mencari nilai minimum di tiap baris (vertikal)

A.min(axis=0)

array([0.34, 0.5 , 0.3 , 0.54])

In [122]:
# Mencari nilai max di tiap kolom (horizontal)

A.max(axis=1)

array([0.55, 0.77, 0.9 ])

In [123]:
A.std()

0.1796910929592474

### MATRIKS

In [124]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [126]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [127]:
np.random.random((3,2))

array([[0.8455284 , 0.56573946],
       [0.38801297, 0.55073566],
       [0.40874396, 0.05366789]])

### MATRIX ARITHMETIC

In [128]:
data = np.array([[1,2],[3,4]])
print(data)

[[1 2]
 [3 4]]


In [129]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [130]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [131]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [132]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


### DOT PRODUCT
dot()

In [134]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)

[[1 2 3]
 [4 5 6]]


In [135]:
print(a_1.shape)

(2, 3)


In [136]:
a_2 = np.array([[7,8], [9,10], [11,12]])
print(a_2)

[[ 7  8]
 [ 9 10]
 [11 12]]


In [137]:
print(a_2.shape)

(3, 2)


In [138]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

### MATRIX INDEXING

In [140]:
data = np.array([[1,2], [3,4], [5,6]])

In [141]:
print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


### MATRIX AGGREGATION

In [142]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [143]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [144]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


### TRANSPOSING
np.T

In [145]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [146]:
print(data.T)

[[1 3 5]
 [2 4 6]]


## RESHAPING
reshape()

In [147]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [148]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [149]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [150]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


### N-DIMENSIONAL ARRAY

In [151]:
ndarr = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

In [152]:
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [153]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [154]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [155]:
print(np.random.random((4,3,2)))

[[[0.2100151  0.8794305 ]
  [0.41733194 0.02328507]
  [0.52390133 0.30801638]]

 [[0.5046906  0.12406342]
  [0.26281783 0.78469755]
  [0.37493252 0.6297542 ]]

 [[0.30889104 0.90188617]
  [0.44923593 0.50670591]
  [0.41514145 0.12119417]]

 [[0.32131508 0.55525417]
  [0.95773105 0.92324445]
  [0.37274626 0.28117098]]]


### FLATTEN N-DIMENSIONAL ARRAY

flatten()
.ravel()

In [156]:
arrflat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [157]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
### WORKING WITH MATH FORMULAS

In [158]:
error = (1/n) * np.sum(np.square(observed - prediction))

NameError: name 'n' is not defined